# Generated by Django 4.1 on 2023-06-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_timeinfo_remove_schedule_exchange_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_account",
            field=models.CharField(max_length=45, verbose_name="계좌번호"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_address",
            field=models.CharField(max_length=45, verbose_name="주소"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_birth",
            field=models.DateField(verbose_name="생년월일"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_email",
            field=models.EmailField(max_length=254, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_gender",
            field=models.CharField(max_length=1, verbose_name="성별"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="직원 사번번호이자 아이디"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_level",
            field=models.CharField(
                choices=[("1", "Lv1_직원"), ("0", "Lv0_매니저")],
                default=1,
                max_length=1,
                verbose_name="접근 권한정보",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_name",
            field=models.CharField(max_length=10, verbose_name="직원 이름"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_phone",
            field=models.CharField(max_length=45, verbose_name="핸드폰번호이자 비밀번호"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_plus",
            field=models.IntegerField(default=0, verbose_name="추가 수당 정보"),
        ),
    ]
