# Generated by Django 4.1 on 2023-06-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_employee_emp_account_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="schedule_exchange", name="schedule1",),
        migrations.RemoveField(model_name="schedule_exchange", name="schedule2",),
    ]
