# Generated by Django 4.1 on 2023-06-06 23:08

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_remove_schedule_exchange_schedule1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule_exchange",
            name="date1",
            field=models.DateField(default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule_exchange",
            name="date2",
            field=models.DateField(default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule_exchange",
            name="end1",
            field=models.TimeField(default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule_exchange",
            name="end2",
            field=models.TimeField(default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule_exchange",
            name="start1",
            field=models.TimeField(default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule_exchange",
            name="start2",
            field=models.TimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
