# Generated by Django 4.1 on 2023-06-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_schedule_exchange_date1_schedule_exchange_date2_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="schedule_exchange", name="date1",),
        migrations.RemoveField(model_name="schedule_exchange", name="date2",),
        migrations.RemoveField(model_name="schedule_exchange", name="end1",),
        migrations.RemoveField(model_name="schedule_exchange", name="end2",),
        migrations.RemoveField(model_name="schedule_exchange", name="start1",),
        migrations.RemoveField(model_name="schedule_exchange", name="start2",),
    ]
