# Generated by Django 4.1 on 2023-06-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0007_schedule_exchange_date1_schedule_exchange_date2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule_exchange",
            name="date1",
            field=models.DateField(default="2023-06-06"),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="date2",
            field=models.DateField(default="2023-06-06"),
        ),
    ]
