# Generated by Django 4.1 on 2023-06-06 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_alter_schedule_exchange_date1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule_exchange",
            name="end1",
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="end2",
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="start1",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="start2",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
