# Generated by Django 4.1 on 2023-06-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0009_alter_schedule_exchange_end1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule_exchange",
            name="end1",
            field=models.TimeField(default="18:00:00"),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="end2",
            field=models.TimeField(default="18:00:00"),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="start1",
            field=models.TimeField(default="09:00:00"),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="start2",
            field=models.TimeField(default="09:00:00"),
        ),
    ]
