# Generated by Django 4.1 on 2023-06-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0010_alter_schedule_exchange_end1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule_exchange", name="date1", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="date2", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="end1", field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="end2", field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="start1", field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="start2", field=models.TimeField(),
        ),
    ]
