# Generated by Django 4.1 on 2023-06-07 01:06

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0011_alter_schedule_exchange_date1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule_exchange",
            name="date1",
            field=models.DateTimeField(default=datetime.date.today().isoformat()),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="date2",
            field=models.DateTimeField(default=datetime.date.today().isoformat()),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="end1",
            field=models.TimeField(default=datetime.date.today().isoformat()),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="end2",
            field=models.TimeField(default=datetime.date.today().isoformat()),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="start1",
            field=models.TimeField(default=datetime.date.today().isoformat()),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="start2",
            field=models.TimeField(default=datetime.date.today().isoformat()),
        ),
    ]
