# Generated by Django 4.1 on 2023-06-07 01:11

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ("management", "0012_alter_schedule_exchange_date1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule_exchange", name="date1", field=models.DateField(default=timezone.now()),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="date2", field=models.DateField(default=timezone.now()),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="end1", field=models.TimeField(default=timezone.now()),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="end2", field=models.TimeField(default=timezone.now()),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="start1", field=models.TimeField(default=timezone.now()),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="start2", field=models.TimeField(default=timezone.now()),
        ),
    ]
