# Generated by Django 4.1 on 2023-06-07 20:52

from django.db import migrations, models
import datetime
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0013_alter_schedule_exchange_date1_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="schedule_exchange", name="date1",),
        migrations.RemoveField(model_name="schedule_exchange", name="date2",),
        migrations.RemoveField(model_name="schedulefix", name="sch_date",),
        migrations.RemoveField(model_name="schedulefix", name="time_end",),
        migrations.RemoveField(model_name="schedulefix", name="time_start",),
        migrations.AddField(
            model_name="schedulefix",
            name="sch_finish",
            field=models.DateTimeField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedulefix",
            name="sch_start",
            field=models.DateTimeField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="end1", field=models.DateTimeField(default=timezone.now()),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="end2", field=models.DateTimeField(default=timezone.now()),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="start1", field=models.DateTimeField(default=timezone.now()),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="start2", field=models.DateTimeField(default=timezone.now()),
        ),
        migrations.DeleteModel(name="Timeinfo",),
    ]
