# Generated by Django 4.1 on 2023-06-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0014_remove_schedule_exchange_date1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule_exchange", name="end1", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="end2",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="schedule_exchange", name="start1", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="schedule_exchange",
            name="start2",
            field=models.DateTimeField(null=True),
        ),
    ]
