# Generated by Django 4.1 on 2023-05-22 11:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("emp_id", models.AutoField(primary_key=True, serialize=False)),
                ("emp_name", models.CharField(max_length=10)),
                ("emp_birth", models.DateField()),
                ("emp_gender", models.CharField(max_length=1)),
                ("emp_address", models.CharField(max_length=45)),
                ("emp_phone", models.CharField(max_length=45)),
                ("emp_account", models.CharField(max_length=45)),
                ("emp_plus", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                (
                    "user_pw",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notice.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                ("not_id", models.AutoField(primary_key=True, serialize=False)),
                ("not_title", models.CharField(max_length=50)),
                ("not_content", models.TextField()),
                ("not_date", models.DateTimeField(auto_now_add=True)),
                (
                    "not_writer",
                    models.ForeignKey(
                        db_column="emp_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notice.employee",
                    ),
                ),
            ],
        ),
    ]
