# Generated by Django 4.1 on 2023-05-27 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={"verbose_name": "공지사항", "verbose_name_plural": "공지사항"},
        ),
        migrations.AddField(
            model_name="notice",
            name="not_hits",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="not_content",
            field=models.TextField(verbose_name="내용"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="not_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="등록시간"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="not_title",
            field=models.CharField(max_length=128, verbose_name="제목"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="not_writer",
            field=models.ForeignKey(
                db_column="user_email",
                on_delete=django.db.models.deletion.CASCADE,
                to="notice.user",
                verbose_name="작성자",
            ),
        ),
        migrations.AlterModelTable(name="notice", table="공지사항",),
    ]
