# Generated by Django 4.1 on 2023-06-06 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0003_employee_emp_email_alter_notice_not_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_email",
            field=models.EmailField(max_length=254, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="not_writer",
            field=models.ForeignKey(
                db_column="user_email",
                on_delete=django.db.models.deletion.CASCADE,
                to="notice.user",
                verbose_name="작성자",
            ),
        ),
    ]
