# Generated by Django 4.1 on 2023-06-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0004_alter_employee_emp_email_alter_notice_not_writer"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="emp_email",),
    ]
