# Generated by Django 4.1 on 2023-06-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0005_remove_employee_emp_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="emp_email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
