# Generated by Django 4.1 on 2023-06-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0006_employee_emp_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="emp_account",
            field=models.CharField(max_length=45, verbose_name="계좌번호"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_address",
            field=models.CharField(max_length=45, verbose_name="주소"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_birth",
            field=models.DateField(verbose_name="생년월일"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_email",
            field=models.EmailField(max_length=254, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_gender",
            field=models.CharField(max_length=1, verbose_name="성별"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="직원 사번번호이자 아이디"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_name",
            field=models.CharField(max_length=10, verbose_name="직원 이름"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_phone",
            field=models.CharField(max_length=45, verbose_name="핸드폰번호이자 비밀번호"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_plus",
            field=models.IntegerField(default=0, verbose_name="추가 수당 정보"),
        ),
    ]
