# Generated by Django 4.1 on 2023-06-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0007_alter_employee_emp_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="emp_level",
            field=models.CharField(
                choices=[("1", "Lv1_직원"), ("0", "Lv0_매니저")],
                default=1,
                max_length=1,
                verbose_name="접근 권한정보",
            ),
        ),
    ]
