# Generated by Django 4.1 on 2023-06-06 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0008_employee_emp_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="not_writer",
            field=models.ForeignKey(
                db_column="emp_email",
                on_delete=django.db.models.deletion.CASCADE,
                to="notice.employee",
                verbose_name="작성자",
            ),
        ),
    ]
